# FROM swr.cn-north-4.myhuaweicloud.com/wlf_darkmaster/pytorch_ascend:pytorch_2.5.1-cann_8.2.rc1-py_3.10-aarch64_0827a
FROM swr.cn-north-4.myhuaweicloud.com/wlf_darkmaster/pytorch_ascend:pytorch_2.5.1-cann_8.2.rc1-py_3.10-aarch64_0827a
# cd /data01/huawei-2025/docker/pkg
# python -m http.server 1111

SHELL [ "/usr/bin/bash", "-c", "-l" ]


# RUN wget -q http://127.0.0.1:1111/Ascend-cann-toolkit_8.3.RC1_linux-aarch64.run ;\
#     bash Ascend-cann-toolkit_8.3.RC1_linux-aarch64.run -q --full --install-path=/usr/local/Ascend ;\
#     rm Ascend-cann-toolkit_8.3.RC1_linux-aarch64.run -f

# RUN wget -q http://127.0.0.1:1111/Ascend-cann-kernels-910b_8.3.RC1_linux-aarch64.run ;\
#     source /usr/local/Ascend/ascend-toolkit/set_env.sh ;\
#     bash Ascend-cann-kernels-910b_8.3.RC1_linux-aarch64.run -q --install --install-path=/usr/local/Ascend ;\
#     rm Ascend-cann-kernels-910b_8.3.RC1_linux-aarch64.run -f

# RUN wget -q http://127.0.0.1:1111/Ascend-cann-nnal_8.3.RC1_linux-aarch64.run ;\
#     source /usr/local/Ascend/ascend-toolkit/set_env.sh ;\
#     bash Ascend-cann-nnal_8.3.RC1_linux-aarch64.run -q --install --install-path=/usr/local/Ascend ;\
#     rm Ascend-cann-nnal_8.3.RC1_linux-aarch64.run -f

# #! 必须要有内部源
# ENV PIP_INDEX_URL=http://pypi.chinatelecom.ai/simple/ \
#     PIP_TRUSTED_HOST=pypi.chinatelecom.ai
RUN pip install glances "ray[default]" debugpy

RUN cd /opt ;\
    rm -rf jemalloc ;\
    tar -zxvf jemalloc.tar.gz ;\
    cd jemalloc ;\
    ./autogen.sh ;\
    ./configure --prefix=/usr/local ;\
    make -j 64 ;\
    make install

#* 迁移代码
# # python -m http.server 1111
RUN cd /tmp; wget -q http://127.0.0.1:1111/libascend_hal.so ;\
    rm -f /usr/local/Ascend/driver/lib64/driver/libascend_hal.so ;\
    cp -f libascend_hal.so /usr/local/Ascend/driver/lib64/driver/ ;\
    cd /opt/ ;\
    rm /opt/vllm.tar.gz -f ;\
    rm /opt/vllm-ascend.tar.gz -f ;\
    wget -q http://127.0.0.1:1111/vllm.tar.gz ;\
    wget -q http://127.0.0.1:1111/vllm-ascend.tar.gz ;\
    rm -rf /opt/vllm ;\
    rm -rf /opt/vllm-ascend ;\
    tar zxvf vllm.tar.gz ;\
    tar zxvf vllm-ascend.tar.gz ;\
    pip uninstall vllm-ascend -y ;\
    pip uninstall vllm -y ;\
    rm /opt/pyvenv/lib/python3.10/site-packages/__editable__.vllm* -f ;\
    sed -i 's/.*vllm-ascend.*//g' /opt/pyvenv/lib/python3.10/site-packages/easy-install.pth

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_RETRIES=5 \
    PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn \
    LD_LIBRARY_PATH=/opt/python3.10/lib/:$LD_LIBRARY_PATH

RUN pip install torch==2.7.1 torchaudio torchvision -i https://pypi.tuna.tsinghua.edu.cn/simple ;\
    pip install torch-npu==2.7.1.dev20250724 --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi
    # # # #! 重新编译 0.10.0 vllm
RUN cd /opt/vllm ;\
    git config --global --add safe.directory /opt/vllm ;\
    VLLM_TARGET_DEVICE=empty pip install -e . -v

# # #! 重新编译 vllm-ascend
# # RUN --mount=type=cache,target=/root/.cache/pip,id=pip \
#! 编译vllm-ascend的时候一定要依赖下载源，否则会找不到 torch_npu，可能设置 TORCH_NPU_PATH 可以规避，还没试过
RUN cd /opt/vllm-ascend ;\
    pip config --global set global.extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi ;\
    git config --global --add safe.directory /opt/vllm-ascend ;\
    pip install -r /opt/vllm-ascend/requirements.txt ;\
    source /usr/local/Ascend/nnal/atb/set_env.sh ;\
    export Torch_DIR=/opt/pyvenv/lib/python3.10/site-packages/torch/share/cmake ;\
    pip install -e . --no-deps -v
# #! 最后对齐版本
RUN pip install "numpy<=1.26.0"

# docker build -f /mnt/hpfs_test/wlf/verl/docker/Dockerfile.verl0928 --network=host -t swr.cn-north-4.myhuaweicloud.com/wlf_darkmaster/pytorch_ascend:pytorch_2.7.1-cann_8.2.rc1-py_3.10-aarch64_0928 .
