# services:
#   A3_83RC1:
#     image: harbor.ai-bj.cn/library/verl:verl_CANN83RC1
#     build:
#       args: [BUILDKIT_PROGRESS=plain]
#       context: .
#       dockerfile: ./Dockerfile.83rc1.cann
#       network: host
services:
  A3_83RC1:
    image: verl:verl_CANN83RC1_A3
    build:
      args: [BUILDKIT_PROGRESS=plain]
      context: .
      dockerfile: ./Dockerfile.A3.83rc1.cann
      network: host

      