FROM quay.io/ascend/cann:8.2.rc1-a3-openeuler22.03-py3.11

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG COMPILE_CUSTOM_KERNELS=1

# Define enviroments
ENV DEBIAN_FRONTED=noninteractive
ENV COMPILE_CUSTOM_KERNELS=${COMPILE_CUSTOM_KERNELS}

RUN yum install -y patch

WORKDIR /workspace

COPY . /vllm-workspace/vllm-ascend/

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Compile/Install apex
RUN git clone -b master https://gitee.com/ascend/apex.git && \
    cd apex/ && bash scripts/build.sh --python=3.11 && \
    cd apex/dist/ && \
    pip3 install --upgrade apex-0.1+ascend-{version}.whl

# verl
RUN git clone https://github.com/volcengine/verl.git && \
    cd verl && \
    git checkout 55e3c

# Megatron-LM
RUN git clone https://github.com/NVIDIA/Megatron-LM.git && \
    cd Megatron-LM && \
    git checkout core_r0.12.0 && \
    cp -r megatron ../verl/

# MindSpeed
RUN git clone https://gitee.com/ascend/MindSpeed.git && \
    cd MindSpeed && \
    git checkout 7ff81 && \
    pip install -r requirements.txt && \
    cp -r mindspeed ../verl/

# Install vLLM
ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
ARG VLLM_TAG=v0.9.1
RUN git clone --depth 1 $VLLM_REPO --branch $VLLM_TAG /vllm-workspace/vllm
# In x86, trition will be installed by vllm. But in Ascend, trition doesn't work correctly, we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -v -e /vllm-workspace/vllm/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y trition && \
    python3 -m pip cache purge && \
    cp -r vllm verl/

# Install vllm-ascend
# Append `libascebd_hal.so` path (devlib) to LD_LIBRARY_PATH
RUN export PIP_EXTRA_INDEX_URL=https://mirrors.huaweicloud.com/ascend/repos/pypi && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    python3 -m pip install -v -e /vllm-workspace/vllm-ascend/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip cache purgeg && \
    cp -r vllm-ascend verl/

# Install modelscope (for fast download) and ray (for multinode)
RUN python3 -m pip install modelscope ray && \
    python3 -m pip cache purge && \
    pip install "transformers<4.54.0" \
    pip install mathruler \
    pip install cbor2 \
    pip install pybase64 \
    pip install openai-harmony

CMD ["/bin/bash"]